### ISSUE TITLE
How beginner-friendly is Groceries to host?

### ISSUE THREAD

**Issue by analpi** [davideshay/groceries#106]
I'm no expert. I've never deployed anything more complicated than an Apache server for a personal website. But Groceries looks like exactly the kind of thing my family needs and I'd love to try my hand at self-hosting it.

But the installation instructions elude me. "Deploy couchDB to a production server ... For couchDB you will also have to enable JWT authentication and set an HMAC key." I mean, I kind of get the gist, but also not really? So what I'm wondering is, if each of those things was broken down into step-by-step instructions, how simple would it be for a beginner to follow them?

I know you've probably got more important things to worry about than writing newbie-friendly instructions, so if you know of any beginner guides to the concepts on the Installation page, I might be able to make do with those.

**Comment by davideshay** [comment]
I think it comes down to if you are familiar with docker-compose at all.  The docker instructions [here](https://davideshay.github.io/groceries/installation/docker-setup/) are basically the easiest approach.  If you extract and expand the docker-full.tar.gz to a new directory and then do docker-compose up in that directory, you should be ok.

That being said, there are a few other mandatory/optional things to do:

- Ideally you should reset the password to couchDB to something other than what I have set it to.  The best way is to change the value in admin.ini and replace it using the information from this [site](https://sleeplessbeastie.eu/2020/03/13/how-to-generate-password-hash-for-couchdb-administrator/).
- If you change the password, change the COUCHDB_ADMIN_PASSWORD environment variables in docker-compose.yaml.
- You should change the "HMAC KEY", basically just a random value that needs to be in the jwt.ini file (as a base64 encoded value) and then in the docker-compose environment variable as a plain-text value.
- The docker-compose file uses caddy -- you need to figure out what the best approach is to make this available on your internal network (access to both couchdb and the auth. server). If you have some experience with caddy/networking/reverse proxies this shouldn't be too bad, but if not this could be a bit of work. Caddy makes it pretty easy in general.

If you try it and run into problems, let me know.
I've also setup a demo site that you can access from [here](https://www.specificallyclementines.com) if you want to try it out. I'm thinking of allowing end-user accounts on this site as well if people don't want to self host, and am waiting for the Android app to be approved in the app store before making that more broadly available.

**Comment by davideshay** [comment]
Closed since no further questions
