### ISSUE TITLE
A link in Documentation leads nowhere.

### ISSUE THREAD

**Issue by Jonny1797** [davideshay/groceries#111]
I just wanted to quickly point out that the link in the [installation documentation](https://raw.githubusercontent.com/davideshay/groceries/master/docs/groceries.yaml) of the [grocery.yaml](https://raw.githubusercontent.com/davideshay/groceries/master/docs/groceries.yaml) leads to a 404.

**Comment by davideshay** [comment]
OK fixed for next release , which I will get out this week.  Out of curiousity, are you trying with this (which was based on kubernetes) or are you using docker compose and the sample docker-compose files?

**Comment by Jonny1797** [comment]
I'm just using docker compose and the sample docker-compose files. I was just curiously looking around and noticed this :blush:.
