### ISSUE TITLE
CouchDB works, backend and frontend not

### ISSUE THREAD

**Issue by Pieeeeeee** [davideshay/groceries#122]
Using docker-compose (Portainer), I managed to get couchDB working, but can't access the frontend or backend.
What I did: 
- curl admin.ini and jwt.ini to the dbetclocal volume.
- create the hmac and pasted it into jwt.ini
- put the plain text version in COUCHDB_HMAC_KEY
- created the pbkdf2 password, put it in admin.ini
- put the plain text user and password in COUCHDB_ADMIN_USER and COUCHDB_ADMIN_PASSWORD

I have Nginx Proxy Manager running in another stack, but to exclude problems with DNS, I'm not using it yet and only using ipadresses in docker compose. I commented out the volumes of the frontend service.

CouchDB is running. I can login and tables are created: _replicator, _users and groceries.
Backend is giving this error: Cannot GET /
Frontend gives error "This site can't be reached". But since the backend doesn't work I'm not focussing on that problem yet.

Any hint on what I might be doing wrong?

[dockercompose-groceries.txt](https://github.com/davideshay/groceries/files/14116998/dockercompose-groceries.txt)

**Comment by davideshay** [comment]
For the backend, can you set LOG_LEVEL to "D" and let me see the full error log for the backend ?
Actually looks like "1" should also be setting it to Debug, so if you can just get me the log that would be helpful.

**Comment by Pieeeeeee** [comment]
Debug only adds 2 lines extra about the jwt token it seems. Added the full log after a restart of the complete stack
[_backend-groceries-server_logs.txt](https://github.com/davideshay/groceries/files/14122326/_backend-groceries-server_logs.txt)

**Comment by davideshay** [comment]
No errors on either the couchdb or backend side.  All looks like "normal" startup.  Can you set the LOG_LEVEL to "D" on the frontend and show me the javascript log from the browser side?

**Comment by Pieeeeeee** [comment]
I will give feedback this weekend, not much time atm

**Comment by Pieeeeeee** [comment]
I found the location of the docker-compose.yml that Portainer created: /var/lib/docker/volumes/portainer_data/_data/compose/31/docker-compose.yml

I then made the directories /data/config and put groceries-web.conf in there, like so:
/var/lib/docker/volumes/portainer_data/_data/compose/31/data/config/groceries-web.conf

But I still get this error:
 invalid mount config for type "bind": bind source path does not exist: /data/compose/31/data/config/groceries-web.conf

**Comment by davideshay** [comment]
I don't know how portainer works at all, sorry, but perhaps you could try to use the docker-simple.tar.gz file on the docker instructions site and see if that works.

**Comment by Pieeeeeee** [comment]
Hey
I picked this up again, and finally got it working. The problem was indeed groceries-web.conf that needed to be linked to /etc/nginx/conf.d/default.conf. I had to do it a little different because of Portainer though.

Another problem I'm having now is getting it to work with my dns.
In my proxy I routed "groceries.mywebsite.com" to 192.168.0.111:8100 (works)
I also routed "groceries.mywebsite.com/api" to 192.168.0.111:3333
But when I use "https://groceries.mywebsite.com/api" as API Server URL in the login page, I get an error "Database Server Not Available".

**Comment by davideshay** [comment]
What are you using to do the routing here?
Are you trying this on Android phone or web browser? If phone, can you try on browser as well?

**Comment by Pieeeeeee** [comment]
I am using Nginx Proxy Manager. The problem was because of adding a custom location "/api" to the proxy host "groceries.example.com". I added a new proxy host "groceriesapi.example.com", and now I can login.

The same was needed for couchdb. I now have 3 different proxy hosts. One for the UI, one for the api and one for couchDB. I wish there was a way to only have one proxy host, since there's a limit on how many Let's Encrypt certificates you can have.

**Comment by davideshay** [comment]
I've used Caddy in docker-compose and nginx-ingress in kubernetes and was able to route the /api path correctly on both.

For Let's Encrypt, I personally use a wildcard certificate and then do all my routing with nginx-ingress in kubernetes.
