### ISSUE TITLE
Issue with Listgroup

### ISSUE THREAD

**Issue by elmodor** [davideshay/groceries#123]
Hi there, thank you for creating a solid alternative for a grocery shopping list!

# Issue
I find the current behavior of the listgroup to be very misleading. As far as I can tell, it seems like the listgroup displays only all items from the first list.

# How to reproduce
1. Create a new server via docker (latest docker-simple.tar.gz)
2. (probably optional) In "Settings" - "Add To Other List Options" set "Don't add automatically"
3. (probably optional, seems to work with the default listgroup too) In "manage all Listgroups" create a new listgroup called "Test List"
4. On "Create New List" create two new list belonging to "Test List" - the first called "List1" and the second called "List2"
5. Go to List1, create a new item: "Item1" (The default settings now is: Active and stocked for List1, stocked for List2)
6. Go to List2, create a new item: "Item2" (Active and stocked for List2, stocked for List1)
7. Go to List2, create a new item: "Item3" but set this Active and stocked for List1 & List2
8. Go to listgroup "Test List"
9. "Test List" only list all items from List1 (Item1, Item3)
10. Notice that "Item2" is missing

# Expected
I would expect one of the following:
* The listgroup "Test List" displays all items that are on the lists within the listgroup (even if the item is only on one list, so: Item1, Item2, Item3)
* The listgroup  "Test List" display only the items that are on every lists within the listgroup (the item has to be on every list to be shown, so: Item3 only)
* (there is an option to select which of the two above should apply)

I usually have items that I only buy at one store only. So I would expect that the listgroup would show me all items on all the lists (e.g. Item1, Item2, Item3)

**Comment by davideshay** [comment]
Fixed in release 1.1.6
