### ISSUE TITLE
Creating new Categories takes a long time for the form to load

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#13]
When I try to create a new Categorie via the Frontend or the App, it shows "Loading Category..." on the top and it seems like nothing happens. I could not spot anything in the Docker logs so far and no "error" in the Browser Debugging Console. But I left it open while I left the computer for an hour and after I came back, the form to create a new categorie was loaded. The Browser Debugging session looks like this (the 50+ minute entry is still counting upwards):

![image](https://user-images.githubusercontent.com/111387593/235300633-4ba1702f-dfa6-4811-98c6-589af84ae197.png)

I have seen in the documentation that the category management is WIP, so I am not sure if this is expected in the current version?

**Comment by davideshay** [comment]
A bug. Will be fixed in next release.

**Comment by davideshay** [comment]
Fixed in release v.0.6.1

**Comment by kladderadeng** [comment]
Wow, that was quick! I downloaded the latest images / apk, tested and it works for me. Thank you very much 😃
