### ISSUE TITLE
2 Admin Users in the jwt.ini

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#15]
I spotted 2 Admin Users in the jwt.ini after initial setup.
These two lines show up as:
"admin" = <secretstuff>
admin = <slightlydifferentsecretstuff>

I suppose that probably in the setup of the Docker Containers either in the CouchDB container or in the Backend Container we need to omit the " when specifying the admin credentials?

Looking at the docs folder in the admin.ini, the entry is without Quotes.
Looking at the docs folder in the docker-compose.yml, both mentions of the admin User use the Quotes and I suppose the Password in clear-text.
Looking at the docs folder in the couchdb.yaml, I see the admin Users mentioned without Quotes, but also that the password should be in PDFKB2 style?
Looking at the docs folder in the groceries.yaml I see that the admin User is mentioned with Quotes and I suppose the Password in clear-text.

I am not too familiar with K8s (the latter 2 yaml are for K8s, right?), but it seems to me that there is a difference between those and the docker-compose.yml.

If I got something wrong, obviously, I wonder why my setup seems to work pretty well? Is one of the 2 admin credentials configured in the yml not even needed maybe?

**Comment by davideshay** [comment]
I'll have to spin up the docker containers again but I believe it's a difference between how the volumes for /opt/couchdb/etc are being treated differently in docker vs. kubernetes. In my kubernetes implementation, I'm mounting a configmap into the admin.ini file, which then makes it read-only, so it never duplicates users -- that is also why the PDFKB2 approach works OK.

**Comment by kladderadeng** [comment]
AFAIK you can mount Volumes / Bindmounts in Docker Read Only by appending a :ro at the end, like
`
volumes:
  - /opt/groceries/couchdb/dbetclocal:/opt/couchdb/etc/local.d:ro
`

But if you mount the whole directory Read-Only, I suppose we run into another problem. K8s is much more flexible in that regard.

**Comment by kladderadeng** [comment]
I am using the app on 2 devices now for a few days and it seems the 2 entries are not causing any issues. So in my opinion we can close this one if this is also OK for you.
