### ISSUE TITLE
Mistake in docs/groceries.yaml sample regarding the HMAC Key?

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#16]
Just an observation:
When creating my containers with a docker-compose.yml, I put the HMAC there in plain text, as the docker-compose.yml in the docs folder seems to propose.
But in the groceries.yaml (K8s?), it is described as a Base64 encoded value. If the containers originate from the same image, I suppose it should be plain-text there too?

The readme.md also makes me believe that the groceries.yaml might contain a mistake:

"The next challenge is setting up the HMAC key. In the jwt.ini file, you need to set the HMAC key. Come up with a random key, and in this file set it to the base64 encoded value. **Later, in the deployment of the groceries auth server, you will use the un-encoded/raw value of this secret key.**"

Further down in the readme.md, probably another mistake:
`COUCHDB_HMAC_KEY: A key (base64 encoded) configured into your couchDB security to allow JWT keys to work.
`

I am not complaining, just trying to help :-)

**Comment by davideshay** [comment]
Thanks so much for the thorough review. I confused myself and in the process the documentation by in my previous implementation using a randomly generated HMAC key -- which was actually in itself base64 encoded. Then I RE-encoded it for the HMAC key in jwt.ini, leading to the documentation errors, although that actually worked.

Ultimately, the env. variable to the auth server needs to have COUCHDB_HMAC_KEY as "plaintext" and then jwt.ini needs to have a base64 encoded value of that key.  I've updated the docs to reflect this now.
