### ISSUE TITLE
[Question] Is there a way to disable the Create User Account button / function?

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#22]
How do you handle that nobody discovering your Web Frontend or the App + API URL can create new Users in your environment? Putting an additional Authentication Layer let´s say on the Reverse Proxy in front of the Web Frontend might work, but not in front of the API. That will break App access. Is there a setting somewhere to disable creating new Users somewhere?

**Comment by davideshay** [comment]
Interesting requirement. I hadn't considered that issue yet. I'm not sure one big "disable" switch is the right answer? It might be simpler to build. Certainly I don't think you want to create the users manually in couchdb.  Maybe some sort of "approval" process? I could create the new user but leave them "disabled" until some flag was changed in the _users database. Eventually I could put a UI on top of that approval process I guess.

I would prefer to use keycloak or some sort of oauth, but that I think is more architecturally complex to do at this point. I have that enabled on other services, but those don't have their own auth. framework too.

Thoughts on what you would want to see in terms of "approval" ?

**Comment by kladderadeng** [comment]
> I'm not sure one big "disable" switch is the right answer? It might be simpler to build. 

That´s exactly what I had in mind. But I am only one User of many of your software. I think it depends what the audience is here. For me, it is just one family using it, I will not host it for the rest of the world or family outside of this household. So creating Users will be a one-time thing and probably never touched again. So being able to enable / disable User creation with a Parameter when starting the Containers or at a similar, "hard" to reach place is totally fine for me.

But if others are hosting it for a bigger audience like dozens or hundreds of people, that what you have in mind would make more sense. I have no overview of  for how many people usually host Groceries, so I can only speak for myself.

It just makes me fell uneasy that everyone can just create new Accounts / Data on a system I host. But I may be overthinking things.

**Comment by davideshay** [comment]
Will go with simple approach for right now. I've added a new environment variable to the backend - DISABLE_ACCOUNT_CREATION that when set to true will not allow any new users to be created via the API.

Will be in next release coming out shortly.
