### ISSUE TITLE
[Question] Correct creation of Unit of Measure and the "ISO" code

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#25]
Another question, now that we use the Application regularly ;-)

We created a new Unit of Measure today, filling out Code (ISO), Description and Plural Description.

Here is the UOM in question:
![image](https://user-images.githubusercontent.com/111387593/236309567-9ac9fd88-aa9c-4538-a18a-65639b09f138.png)

Then when using it in a List, it looks like this:
![image](https://user-images.githubusercontent.com/111387593/236309634-ca0f2203-9bd1-4b9f-bd73-04db280af551.png)

I suppose this is because I am not using the ISO Code for the Unit. But I have a hard time finding a ISO Code list for Units of Measure. I always end up in lists with ISO codes for countries and other stuff. You do not happen to have a link with a list about what ISO codes are valid to use?

**Comment by davideshay** [comment]
Couple of things on this one:

1. There is nothing magical about the code/abbreviation you use.  It's really just a "key" for the UoM descriptions.  I think I actually used EDI/X.12 codes, here is an example site: [https://ediacademy.com/blog/x12-unit-of-measurement-codes/](https://ediacademy.com/blog/x12-unit-of-measurement-codes/)
2. Not sure if you were going for bag or bottle, but both are built in to the standard UoM set. Bags as BG and Bottles as BO. It's possible the translations of these are off, though. I translated BG/Bags to "Tüte" and BO/Bottles to "Flasche". Let me know if these translations are off.
3. The display like that was just a bug -- guess I never tested the translations of new/custom units in that spot. It is fixed now and will be in the next release, probably this weekend.

**Comment by kladderadeng** [comment]
1. All clear and thanks for the link :-)
2. I think Tüte for Bag is perfect, the same for Flasche as Bottle. I think Beutel is more like pouch in english, at least that´s the best translation I was able to find. Depending on the context, it is possible that there is not much difference in German between Tüte (Bag) and Beutel (Pouch). But my partner is veeery precise when making lists 😆 
3. Awesome and thank you very much :-)

**Comment by davideshay** [comment]
Bug fix now released in 0.7.3

**Comment by kladderadeng** [comment]
Tested and works. That fixed it from displaying "1 uom.BTL" to "1 Beutel" as expected. Thank you very much :-)
