### ISSUE TITLE
[Behaviour] Android App logging out unexpectedly

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#26]
Yesterday when I was out shopping, I realized that the Android App showed offline in the top right symbol, although I thought I had a good reception. I closed the app and opened it again and it showed me the login screen. That is a bit unfortunate when the password you use is in your password manager... at home 😆 

So slightly out of panic and out of curiosity I just entered a random string in the password field and I was "logged" in again in Offline mode and finished my shopping spree.

Back home I restarted the app again, entered the right password and everything was syncing up again, no problem.

Bein "offline" initially in the store was not a problem with the App, I am sure. But being logged out was unexpected to me. I have difficulties replicating it reliably, so at the moment I can only guess. Is there a log of some sorts or something I should look out for when this happens again, so I have a chance to find the reason why the app is not starting in "offline" mode, but reverting back to the login screen?

When I am out on the road, I think I change cell phone masts very often, sometimes the phone sees public wifis and sometimes just has no reception at all. Could these be reasons for the JWT token to become invalid and the app is starting with the login screen maybe?

**Comment by davideshay** [comment]
I fixed one small bug in this regard, but don't think it was causing issues beyond the second login.

In any case, I've added some additional logging to the backend, which now has timestamps. You can set "LOG_LEVEL" to "DEBUG" on the groceries server and will now get more data on all events related to sign-ins and token expiration. The front-end will also log more, but if you are using it in Android it's not easy or maybe even possible to get those logs off the device. Hopefully can diagnose from the backend. Install 0.7.3 and enable the debug logging on the backend, then we can see if it happens again if there is a log file to check.

**Comment by davideshay** [comment]
Fixed another issue which may have been the one causing your problems. If you start the app "fresh" rather than continue in an existing session, you would not be offered the prompt to work offline. I had built this logic previously but lost it in a refactor somewhere along the way.  Even if this wasn't what you saw, this was an issue for sure.

**Comment by kladderadeng** [comment]
Sorry for the late response. It was just today when I went shopping again and got logged out. When entering the 2nd shop on my tour I saw that the app showed me offline on the top right. It was no problem, since you can continue shopping fine in offline mode, very well done :-)
After I was done, I closed the app and opened it again. It showed me the login screen and a "JWT invalid" message. It is only that I am at home now and I tried to go through the logs of the groceries-backend. When I look at all the DEBUG messages (Valdidating token...) I only see messages with "isValid: true". I expected to see one with "isValid: false". So I am not sure if the problem maybe happend on the device and not on the server. Otherwise I should spot a message with "isValid: false", or what should I look out for to give you valuable information?

I made sure I run the latest containers and android app before I left the house.

The logout is not an issue, since I changed my password to something I can remember and can easily log in again when on the road. Oh, and shopping with groceries is a joy. My partner has a lot of fun watching live as I mark shopped items from the list while I am on my tour :-)

**Comment by davideshay** [comment]
Probably this weekend will have a new release solving a lot of these online/offline challenges and making it more robust.
I think I've already solved part of this bug (not yet released...) -- for reference, though, what values are you using as env. variables on the backend -- "REFRESH_TOKEN_EXPIRES" and "ACCESS_TOKEN_EXPIRES" ? Or are they the defaults?  I think what might have happened is that in some cases where the when I was refreshing the token while the app was running, the refresh token wasn't being stored, leading to future problems.

**Comment by davideshay** [comment]
Please test v0.7.6 just released - it should have much more robust logic around online/offline transitions.

**Comment by kladderadeng** [comment]
@davideshay I wanted to give you an update, since I had a few shopping tours now since the last update and I am happy to say that I did not had any unexpected logouts again. Even when losing reception, I had no issues. The app just switched to offline mode and when I had reception again, switched to Online. No need to log in again. It works great now. Thank you very much :-)
