### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by LeoKlaus** [davideshay/groceries#3]
If you offer translation support, I could translate from English to German.

**Comment by owmsoton** [comment]
I can translate from English to Brazilian Portuguese (pt_BR)

**Comment by davideshay** [comment]
Just released the internationalization release. I pre-created Spanish and German translations, but they were ChatGPT so will inevitably need much rework. @LeoKlaus , please review the existing German ones. @owmsoton , happy to accept a new translation file from the base in the client/src/locales/en directory for Brazilian Portugese.
