### ISSUE TITLE
After Android App Update stuck on Login Page

### ISSUE THREAD

**Issue by MariusSp** [davideshay/groceries#39]
I updated my mobile apps as well as the server components. Now the Android Apps are stuck on the Login screen and i cannot change the remote address or anything else. Web client in the browser still works fine. Reinstall does not help.

![Screenshot_20230608-104138_groceries](https://github.com/davideshay/groceries/assets/35237005/07c9ad6c-a006-4cf7-85ce-7ae6813327a2)
![Screenshot_20230608-104141_groceries](https://github.com/davideshay/groceries/assets/35237005/41145b48-caaf-4814-bd52-c74f67e482e6)

**Comment by MariusSp** [comment]
Clearing cache, storage or reinstalling does not help. Using Android 13.

**Comment by davideshay** [comment]
If you enable debug logging on the backend server (setting environment
variable LOG_LEVEL to "DEBUG"), do you see any connections attempting to be
made there?
This was previously working? Which release are you using?

**Comment by davideshay** [comment]
Was able to reproduce finally. I have provided a new release v0.7.9 that should have these fixed. Let me know. May need to do one more uninstall/clear storage to get it fixed.

**Comment by MariusSp** [comment]
Thank you for your effort!

The upgrade process worked on 1/3 devices, two showed the conflict alert.

The login page is fixed on all of them
