### ISSUE TITLE
Add Confirmation Dialog to "Delete completed Items" Button.

### ISSUE THREAD

**Issue by MariusSp** [davideshay/groceries#41]
The mentioned Button is pretty large and sometimes overlayed with the FAB "Add Item" button. A missclick on the ladder can lead to the "deletion" of the completed item list.

This could be avoided with an extra confirmation on the Delete button.
![Screenshot_20230610-085103](https://github.com/davideshay/groceries/assets/35237005/4aa70f18-9793-4475-bfdd-2eb296fa9dd0)

**Comment by davideshay** [comment]
Confirmation dialog added in v0.8.0. Please verify.

**Comment by MariusSp** [comment]
Looks good, thank you!
