### ISSUE TITLE
Adding Photo from "Gallery" is not working anymore

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#45]
Hi there,

one of the latest updates seems to have broken the function to add a photo to an item from your gallery.

How to reproduce:
Edit an existing item and select Take Photo. The app asks you if you want to add one from your gallery or if you want to take a new photo. If you select gallery, nothing happens. If you select take a new photo, you can take a new photo. So the latter one still works.

What did I try to solve this?
In Android I went to the App settings to the permissions because I thought maybe Groceries is not having acces to the gallery anymore, but Android tells me that this app is not requesting any permissions, so I am not able to set any.

Version we tried: 0.8.0
OS: Android 13, Lineage OS 20-20230610

Devices we tried:
- Poco F1
- Mi9 Lite

**Comment by davideshay** [comment]
Odd. Yes I have been able to reproduce and will look into a fix. As a temporary workaround, use the mobile browser on the android phone and you can select an existing photo. Must have been a capacitor upgrade that broke something.

**Comment by davideshay** [comment]
Will be fixed in next release 0.8.1.  Android 13 needs to now have a permission in AndroidManifest.xml for "READ_MEDIA_IMAGES".

**Comment by kladderadeng** [comment]
Oh, that's cool that you found a solution so quick. Thank you very much. :-)

**Comment by davideshay** [comment]
v0.8.1 released - let me know if that fixes it.

**Comment by kladderadeng** [comment]
I just updated and tested it. It works again, Thank you so much.

Also the upgrade process got very smooth since a few versions. I do not need to uninstall the app before installing it again and after updating I am still signed in. This is very robust now. I need to spread the word more in the Selfhosted communities :-)
