### ISSUE TITLE
APK at release v0.8.1 has wrong versionName

### ISSUE THREAD

**Issue by IzzySoft** [davideshay/groceries#47]
The APK at release v0.8.1 identifies as

    package: name='io.ionic.starter' versionCode='80' versionName='0.8.0'

Guess you forgot to adjust the version?

PS: `io.ionic.starter` sounds like the default `applicationId` set for demonstration purposes (aka "this is an ionic app"; the launcher icon also looks like it's standing for Capacitor instead of for a groceries app). Is that intended? Won't it collide with other apps? Not that I encountered one yet, so I just wonder.

**Comment by davideshay** [comment]
Changed and fixed in release 1.0.0 -- read release notes as you must also uninstall groceries and install APK with the new name.

**Comment by IzzySoft** [comment]
There's no way to notify existing users about that I'm afraid. I've established it as a separate app for now, including a hint with the original one. The latter will be removed in about 2 months then, to give folks a chance to notice and switch.

Thanks!

**Comment by davideshay** [comment]
I think if they try to access the new backend server with an old client, it
will notify you and not allow it. So that SHOULD work that way... There's
always a chance it's broken...

**Comment by IzzySoft** [comment]
That's the best we can do then I'd say. Thanks!
