### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by aleksasiriski** [davideshay/groceries#5]
Why couchDB instead of Postgres?

Why MIT instead of AGPLv3?

**Comment by davideshay** [comment]
This app is all about sync first and an ability to operate offline if necessary.  The best thing about pouchdb/couchdb is just how well the sync works. I've tried many of the grocery apps on the app stores and didn't find anything that had sync that works as effectively and simply as pouch/couch.

As for licensing, I just want this to be as permissive as possible. If someone else wants to do something with it, more power to them.
