### ISSUE TITLE
[Cosmetic] Box for Checkmarks goes slightly off-screen when having 3 lines for an item

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#51]
Hello there,

first, thank you very much for keeping this updated. Also in a way that no update yet broke anything and was just a docker-compose up -d and we´re done :-)

But I got a complaint from my partner in with the latest Update of the Android app. The issue is, that she has a slightly bigger font configured for her Android phone, which works systemwide and for all apps as far as I know. This was not an issue with the last groceries version, but now that we went to 1.0 she realized that the boxes for the checkmarks go off-screen a bit when she has more than 2 lines for an item and even if it are only 2, they hardly fit into the "boundaries".

This is not a problem you introduced in v1.0, I think it is just that the font size she uses it a bit bigger than the system default. Because of that I flagged that as [Cosmetic].

I think (if possible), it could help if each item has a flexible size instead of a size that usually can accomodate 2 lines and is fixed. I have no idea how hard it is to implement, but it would be fantastic if the section for an item would be rendered depending on how much is in it. I will try to attach a picture, so you can see what I mean.

Thanks again for everything you have done so far, we really enjoy using the app :-)

![image](https://github.com/davideshay/groceries/assets/111387593/9798f6e5-cd30-46fd-a19f-97979a5fbe97)

**Comment by davideshay** [comment]
Have to admit I hadn't tested multi-line item names, but yeah looks off. Fixed in v1.0.1.

**Comment by kladderadeng** [comment]
Holy smokes! How did you fix that so quick! 🥇 
Thank you very much! It looks VERY good now, even if you crank up the font size in Android to eleven.

The only think I noticed is when we downloaded the current .apk, that it did not want to upgrade because the same app (version?) is already installed. I had to uninstall the old version and then install the new version. This is not a big deal, but I just wanted to mention it, because you mentioned in the 1.0.0 release notes that you follow android standards regarding versioning. But maybe that is not related.

**Comment by davideshay** [comment]
v1.0.2 now released which now has a signed release with the same key every time. To install the 1.0.2 release you will have to uninstall/reinstall again, but if all goes well for v1.0.3 and later the upgrade should go through automatically.

**Comment by kladderadeng** [comment]
Awesome, Thank you very much. Updating will be so much easier with Google Play (or maybe F-Droid?) if this happens in the future :-)
