### ISSUE TITLE
[Bug] Error Loading Item Information... Restart.

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#56]
We have an item in our list that we can neither edit nor delete. We can check / uncheck it still, but everything else leads to this error message in the Subject. We see the same in the Android App and also in the Web Frontend.
I had a look at the logs of the Backend, Frontend and CouchDB containers, but was not able to identify an error message there. LOG_LEVEL on the Backend Container is set to DEBUG already, but maybe the error happens in the frontend and app? The conflicts log in the Frontend / App is empty. Is there anything else I can look out for to have a chance to identify the root cause?

**Comment by kladderadeng** [comment]
Thank you very much for your quick response. I set the Environment Variable LOG_LEVEL: "D" on the container that is running the image groceries-client and restarted the whole stack (CouchDB, Backend, Frontend).
I then used an in-private Browser session with the Dev Tools enabled and tried to open the item that causes the error. This is what I see in the console:
![image](https://github.com/davideshay/groceries/assets/111387593/df43ae37-3698-4edd-bf7c-c50e391f1668)

But since this is the same as I was able to see without LOG_LEVEL: "D", I am not sure if it really changed the log level as you expected. Did I miss something or is this really information that makes sense to you?

**Comment by kladderadeng** [comment]
Oops, sorry. I misunderstood. I thought you mean waiting for 1.0.2 for easier debugging, but I can use the Web frontend + Console to help tracking it down now :-) I'll wait of course. I mean, everything works fine and that item causes no other issues when using the application. Take your time, please.

**Comment by davideshay** [comment]
v1.0.2 released which has extra debugging.  Let me know when you have a console log.

**Comment by kladderadeng** [comment]
Thank you! I upgraded and repeated my test. There is a bit more information in the Log now. I was not sure what exactly to look for, so if there is something missing, please let me know.
The only thing I spotted is that the itemError is false, but the imageError is true. That, together with the errors on the top of the list, does that mean it expects the Item to have a picture attached, but it can not be found?

![image](https://github.com/davideshay/groceries/assets/111387593/f926c479-234c-4c7b-94bb-ed6771f78666)

**Comment by kladderadeng** [comment]
Just a thought: Remember when there was a problem with adding pictures to items for a short period of time? Right after you released a new apk with a fix, I upgraded, opened a random item and added a random picture to it. I saw that it works, removed the picture again and gave you feedback that it works again.
What if that random Item I picked was the one that is causing the error now? Maybe adding / removing the picture very quickly caused a problem in the sync process? The database now has the information that a picture is existing for the item, but it is not anymore.
Is that a possibility?

**Comment by davideshay** [comment]
Yes it was the images... Nothing corrupted there exactly, but in v1.0.0, I started using a "replication filter" to only replicate your specific list group/list data to your local devices. Unfortunately I somehow missed including photos/images in that filter, so it wasn't sending that image down to the local device, then when it looked for it the image wasn't there.

In any case, this is now fixed in v1.0.3, and any images you had prior to v1.0.0 will be retained. If you happened to take any pictures between that release and now (last 12 days or so), then those will unfortunately be lost.  Not very easy to recover them otherwise.

Let me know if v1.0.3 fixes it.

**Comment by kladderadeng** [comment]
Thank you so much! I updated the containers and the app on the Android devices and it looks good now. I am able to open the item in question (which was indeed the one with the test picture) and can edit again (removing the picture for example) :-)
