### ISSUE TITLE
Feature request: Build docker images for armv7

### ISSUE THREAD

**Issue by devmotion** [davideshay/groceries#67]
Hi!

I'd like to install Specifically Clementines on a Beaglebone Black. I guess I could try to perform a manual installation but I think it would be much easier (also for keeping the app updated) if I could run and update a pre-built docker image. Would it be possible to add an official armv7 docker image?

**Comment by davideshay** [comment]
Added now in release 1.0.4.   Had to move away from the alpine image for the client nginx application and add some extra steps to the dockerfile to allow for building on arm32. I no longer have arm32 devices, so please test and let me know if it works.

**Comment by davideshay** [comment]
Closed as completed. Let me know if there are issues.
