### ISSUE TITLE
Category selection dropdown only shows first six entries+no scrolling

### ISSUE THREAD

**Issue by MariusSp** [davideshay/groceries#87]
This happens on the Editing Item page. cf screenshot

![image](https://github.com/davideshay/groceries/assets/35237005/6605eba7-431c-4d37-ac1b-e72a4a13db06)

I have more than six categories. I would expect the dropdown to be longer or scroll down to more entries.

**Comment by davideshay** [comment]
Can you give any more information on this one, including which screen this is happening on, and perhaps a screenshot?

**Comment by MariusSp** [comment]
updated original comment

**Comment by davideshay** [comment]
I don't think this is a scrolling problem, but rather the data that is being populated in the list. Right now, the logic for that dropdown only shows categories in the drop-down that are "enabled" across the complete set of lists in the list group. Can you take a look at / post screenshots of the list editor for each of the lists in this list group?

**Comment by MariusSp** [comment]
You are right, the missing categories were flagged as inactive in the edit list screen. 

Sorry for the false alarm and thankyou for the help.
