### ISSUE TITLE
[Feature Request] Would it be possible to see which lists contain unchecked items?

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#91]
As we create more and more shopping lists we came up with the idea that it would be neat to see in the list drop down which list still contains unchecked items. Maybe with a small blue dot in front of the name or it being bold or something else.

When on a shopping tour, to not miss anything, currently you have to open each list to see if something is still missing or if you can finally ;-) drive home to put your loot into the stash.

It is not an important feature, but we thought it would be neat to have some sort of visual indicator in the list drop down to quickly see if you have missed something.

**Comment by davideshay** [comment]
Included in release 1.0.6 - blue dot on right hand side of lists / list groups with unchecked items.

**Comment by kladderadeng** [comment]
I´m speechless! Absolutely incredible. Thank you so much :-)
