### ISSUE TITLE
Backend server fails creating database

### ISSUE THREAD

**Issue by surdy** [davideshay/groceries#92]
Using latest (v1.0.5) with default docker-compose setup from the [docs](https://davideshay.github.io/groceries/installation/docker-setup/). I must be doing something incredibly stupid because the backend server container fails as its unable to create the groceries database. 

```
backend-groceries-server     | [04:54:07] INFO: Starting up auth server for couchdb...
backend-groceries-server     | [04:54:07] INFO: App Version:  1.0.5
backend-groceries-server     | [04:54:07] INFO: Database Schema Version: 5
backend-groceries-server     | [04:54:07] INFO: Database URL:  http://localhost:5984
backend-groceries-server     | [04:54:07] INFO: Internal Database URL:  http://couchdb:5984
backend-groceries-server     | [04:54:07] INFO: Using database: groceries
backend-groceries-server     | [04:54:07] INFO: Refresh token expires in  30d(2592000 seconds)
backend-groceries-server     | [04:54:07] INFO: STATUS: Access token expires in  12h(43200 seconds)
backend-groceries-server     | [04:54:07] INFO: STATUS: User Account Creation is:  ENABLED
backend-groceries-server     | [04:54:07] ERROR: could not retrieve database info.
backend-groceries-server     | [04:54:07] INFO: Database does not exist... Creating....
backend-groceries-server     | [04:54:07] ERROR: Could not create new database
backend-groceries-server     | [04:54:07] INFO: Database existence checked/created.
backend-groceries-server     | ---ERROR IN STARTUP--- EXITING BACKEND
backend-groceries-server exited with code 1
```

Going to the url http://<host_ip>:5984/_utils/ I was able to login with the default username/password. Under databases I see `_users` and `_ replicators`. Under settings I did see the user/password correctly created.

Docker 20.10 , Docker Compose 1.29 , Debian 12

Any suggestions for debugging this ?

**Comment by davideshay** [comment]
I've fixed up the docker-compose examples in 1.0.6 which will be releasing this weekend. In the meantime try adding "restart: unless-needed" to the backend-groceries-server service, at the same indent level as "container_name:"

**Comment by davideshay** [comment]
Release 1.0.6 now published. Please let me know if you have any other questions.

**Comment by surdy** [comment]
Thanks so much for the prompt response. I will try it out this weekend and report back.

**Comment by surdy** [comment]
I got past the issue with backend server with 1.0.6. Thanks so much :-) . I did run into other issues but I will save that for another github issue.
